// Generated by wiki/tools/build_fandom_index.py -- do not edit by hand.
export default [
  {
    "text": "游戏作品",
    "items": [
      {
        "text": "Saga of the Dead Wiki",
        "link": "/fandom/saga-of-the-dead-wiki"
      },
      {
        "text": "Road of the Dead",
        "link": "/fandom/road-of-the-dead"
      },
      {
        "text": "Road of the Dead 2",
        "link": "/fandom/road-of-the-dead-2-2"
      },
      {
        "text": "Lab of the Dead",
        "link": "/fandom/lab-of-the-dead-2"
      },
      {
        "text": "Range of the Dead",
        "link": "/fandom/range-of-the-dead"
      },
      {
        "text": "Segway of the Dead",
        "link": "/fandom/segway-of-the-dead"
      },
      {
        "text": "Streets of the Dead",
        "link": "/fandom/streets-of-the-dead"
      },
      {
        "text": "游戏模式",
        "link": "/fandom/gamemodes"
      },
      {
        "text": "RotD3 泄露",
        "link": "/fandom/rotd3-leak"
      },
      {
        "text": "Lab of the Dead 的灵感来源",
        "link": "/fandom/the-inspiration-for-the-lab-of-the-dead"
      },
      {
        "text": "EvilDog Games",
        "link": "/fandom/evildog-games"
      }
    ]
  },
  {
    "text": "角色",
    "items": [
      {
        "text": "约翰·克里斯曼",
        "link": "/fandom/john-creasman"
      },
      {
        "text": "约翰尼",
        "link": "/fandom/johnny"
      },
      {
        "text": "艾伦·C·泰勒",
        "link": "/fandom/allen-c-tyler"
      },
      {
        "text": "黛安·罗斯沃斯",
        "link": "/fandom/diane-roseworth"
      },
      {
        "text": "科切塔·所罗门",
        "link": "/fandom/cocheta-solomon"
      },
      {
        "text": "洛里·本尼迪克特",
        "link": "/fandom/lori-benedict"
      },
      {
        "text": "谢尔曼将军",
        "link": "/fandom/general-sherman"
      },
      {
        "text": "角色",
        "link": "/fandom/characters"
      },
      {
        "text": "军事指挥官",
        "link": "/fandom/military-commander"
      },
      {
        "text": "阿尔法小队",
        "link": "/fandom/alpha-team"
      },
      {
        "text": "Evil-Dog",
        "link": "/fandom/evil-dog"
      },
      {
        "text": "SickDeathFiend",
        "link": "/fandom/sickdeathfiend"
      }
    ]
  },
  {
    "text": "敌人与阵营",
    "items": [
      {
        "text": "普通丧尸",
        "link": "/fandom/common-undead"
      },
      {
        "text": "阿尔法突变体",
        "link": "/fandom/alpha-mutants"
      },
      {
        "text": "鬼面兽",
        "link": "/fandom/brutes"
      },
      {
        "text": "暴食者",
        "link": "/fandom/feeders"
      },
      {
        "text": "蛆虫",
        "link": "/fandom/grub"
      },
      {
        "text": "变异丧尸",
        "link": "/fandom/mutant-zombies"
      },
      {
        "text": "掠夺者",
        "link": "/fandom/ravager"
      },
      {
        "text": "丧尸士兵",
        "link": "/fandom/undead-soldier"
      },
      {
        "text": "丧尸特警",
        "link": "/fandom/undead-s-w-a-t-officer"
      },
      {
        "text": "丧尸警察",
        "link": "/fandom/undead-police-officer"
      },
      {
        "text": "亡者防暴警官",
        "link": "/fandom/undead-riot-control-officer"
      },
      {
        "text": "军队士兵",
        "link": "/fandom/military-soldier"
      },
      {
        "text": "军事单位",
        "link": "/fandom/military-units"
      },
      {
        "text": "军方",
        "link": "/fandom/military"
      },
      {
        "text": "平民",
        "link": "/fandom/civilians"
      }
    ]
  },
  {
    "text": "武器",
    "items": [
      {
        "text": "武器",
        "link": "/fandom/weapons"
      },
      {
        "text": "手枪",
        "link": "/fandom/pistol"
      },
      {
        "text": "左轮手枪",
        "link": "/fandom/revolver"
      },
      {
        "text": "车载武器",
        "link": "/fandom/mounted-weapons"
      },
      {
        "text": "机枪炮塔",
        "link": "/fandom/machine-gun-turret"
      },
      {
        "text": "武器补给点",
        "link": "/fandom/weapon-caches"
      }
    ]
  },
  {
    "text": "载具",
    "items": [
      {
        "text": "悍马",
        "link": "/fandom/humvee"
      },
      {
        "text": "地狱火",
        "link": "/fandom/hellfire"
      },
      {
        "text": "攻击直升机",
        "link": "/fandom/attack-choppers"
      },
      {
        "text": "支援直升机",
        "link": "/fandom/support-choppers"
      },
      {
        "text": "轰炸机",
        "link": "/fandom/bomber-jet"
      },
      {
        "text": "幻影鹰",
        "link": "/fandom/phantom-eagle"
      },
      {
        "text": "废弃车辆",
        "link": "/fandom/abandoned-vehicles"
      },
      {
        "text": "军用车辆",
        "link": "/fandom/army-vehicles"
      },
      {
        "text": "大型车辆",
        "link": "/fandom/large-vehicles"
      },
      {
        "text": "行驶中的汽车",
        "link": "/fandom/moving-cars"
      },
      {
        "text": "油罐车",
        "link": "/fandom/fuel-trucks"
      },
      {
        "text": "约翰·克里斯曼的汽车",
        "link": "/fandom/john-creasman-s-car"
      }
    ]
  },
  {
    "text": "地点",
    "items": [
      {
        "text": "埃文斯城",
        "link": "/fandom/evans-city"
      },
      {
        "text": "士兵眼中的埃文斯城",
        "link": "/fandom/evans-city-from-soldiers"
      },
      {
        "text": "塞诺亚",
        "link": "/fandom/senoia"
      },
      {
        "text": "65 号公路",
        "link": "/fandom/highway-65"
      },
      {
        "text": "检查站",
        "link": "/fandom/checkpoints"
      },
      {
        "text": "修车厂",
        "link": "/fandom/garages"
      },
      {
        "text": "教堂",
        "link": "/fandom/churches"
      },
      {
        "text": "警察局",
        "link": "/fandom/police-stations"
      },
      {
        "text": "埃文斯城警察局",
        "link": "/fandom/evans-city-police-department"
      }
    ]
  },
  {
    "text": "道具与机制",
    "items": [
      {
        "text": "特长",
        "link": "/fandom/perks"
      },
      {
        "text": "驾驶技能",
        "link": "/fandom/driving-skills"
      },
      {
        "text": "生存指南",
        "link": "/fandom/survival-guide"
      },
      {
        "text": "医疗针剂",
        "link": "/fandom/medical-shots"
      },
      {
        "text": "动作感应地雷",
        "link": "/fandom/motion-detector-mines"
      },
      {
        "text": "地雷",
        "link": "/fandom/mines"
      },
      {
        "text": "消防栓",
        "link": "/fandom/fire-hydrants"
      },
      {
        "text": "漏油",
        "link": "/fandom/oil-spills"
      },
      {
        "text": "安全围栏",
        "link": "/fandom/security-fences"
      },
      {
        "text": "钉刺带",
        "link": "/fandom/spike-strips"
      },
      {
        "text": "水桶",
        "link": "/fandom/water-barrels"
      },
      {
        "text": "尸体",
        "link": "/fandom/corpses"
      },
      {
        "text": "西瓜日（彩蛋）",
        "link": "/fandom/watermelon-day-easter-egg"
      },
      {
        "text": "Road of the Dead 2/升级",
        "link": "/fandom/road-of-the-dead-2-upgrades"
      }
    ]
  },
  {
    "text": "剧情与世界观",
    "items": [
      {
        "text": "时间线",
        "link": "/fandom/timeline"
      },
      {
        "text": "丧尸病毒",
        "link": "/fandom/zombie-virus"
      },
      {
        "text": "阿尔法录音带",
        "link": "/fandom/alpha-tapes"
      },
      {
        "text": "阿尔法笔记",
        "link": "/fandom/alpha-notes"
      },
      {
        "text": "我所看到的",
        "link": "/fandom/what-i-saw"
      },
      {
        "text": "Road of the Dead/对话",
        "link": "/fandom/road-of-the-dead-dialogue"
      },
      {
        "text": "Road of the Dead 2/对话",
        "link": "/fandom/road-of-the-dead-2-dialogue"
      }
    ]
  }
]
